### ISSUE TITLE
Nav Bar and Carousal for Desktop

### ISSUE THREAD

**Issue by prateekrawal** [zero-gravity-org/zero-gravity-website#1]
Refer to Wireframes for the picture.
1. Background of Nav Bar need to be transparent so that pictures of carousal act as its background.
2. 5 picture in carousal with 3 sec limit for each
3.  On hovering each button of navbar (top and down border) needs to be visible of color same as "donote" button.

**Comment by Vaibhav015** [comment]
Hey @prateekrawal :wave: I'll like to work on this issue!

**Comment by coderwassananmol** [comment]
Feel free to assign yourself.

**Comment by Vaibhav015** [comment]
> Feel free to assign yourself.

I guess I don't have permission to assign it myself :sweat_smile:

**Comment by coderwassananmol** [comment]
> > Feel free to assign yourself.
> 
> I guess I don't have permission to assign it myself

Feel free to make Pull Request to dev branch. Fork the repo and create PR to dev. Read Contributing guidelines for more details.

**Comment by prateekrawal** [comment]
@Vaibhav015 Please take up issue of "who we are section" as well, see wire frames for more info, it overlaps with carousal

**Comment by Vaibhav015** [comment]
> @Vaibhav015 Please take up issue of "who we are section" as well, see wire frames for more info, it overlaps with carousal

okay I'll do it :+1: :blush:

**Comment by himadrinayak** [comment]
Hi! i want to work on this issue. Can you pls assign this to me. @prateekrawal

**Comment by coderwassananmol** [comment]
@

> Hi! i want to work on this issue. Can you pls assign this to me. @prateekrawal

Feel free to send PR.

**Comment by sahilit** [comment]
@prateekrawal  @coderwassananmol 
Hey, I have created this carousel and a navbar for a project.
Demo: https://reshape.herokuapp.com/
Code: https://github.com/sahilit/Reshape
The original project is in PHP but I can make it using javascript without any problem.
Can we use this design and carousel?

**Comment by coderwassananmol** [comment]
Issue resolved.
