### ISSUE TITLE
Fund ed program and how can you help section

### ISSUE THREAD

**Issue by prateekrawal** [zero-gravity-org/zero-gravity-website#12]
Refer Designs on figma.
For Links to be associated with each button plz contact me

**Comment by vaibhav-sharma-frontend** [comment]
I would like to work on it.

**Comment by prateekrawal** [comment]
Ok go ahead

**Comment by coderwassananmol** [comment]
@vsharma20v Are you working on it?

**Comment by vaibhav-sharma-frontend** [comment]
@coderwassananmol  I already submitted a PR and that was merged if I'm not wrong.
Reference: https://github.com/zero-gravity-org/zero-gravity-website/pull/18#issue-262706948
