### ISSUE TITLE
Embed Google Form for database of donors

### ISSUE THREAD

**Issue by coderwassananmol** [zero-gravity-org/zero-gravity-website#3]
A Google Form has to be embed in the website.

**Comment by abdus** [comment]
I want to work on this issue.

**Comment by coderwassananmol** [comment]
Feel free to send PR! @thisisabdus

**Comment by kgupta786** [comment]
I want to work on this issue
So can you tell me what details you want to show in google form?

**Comment by prateekrawal** [comment]
@kgupta786
This is abdus is working on this
I will add more issues tonight
Please claim that

**Comment by kgupta786** [comment]
ok sure

**Comment by coderwassananmol** [comment]
@thisisabdus Updates on the issue?

**Comment by kgupta786** [comment]
Can I take this issue now?

**Comment by kgupta786** [comment]
> A Google Form has to be embed in the website.

Can you tell me what type of questions do we need to embed in google form?

**Comment by coderwassananmol** [comment]
You can take these questions for now:
1. Full name[required]
2. E-Mail[required]
3. Mobile Number[required]
4. Why would you like to make a donation?[required]
5. Any suggestions for us?[optional]
Please note that the questions might change over time and the author of merged PR will be responsible to change the questions later.
