### ISSUE TITLE
Embed YouTube videos

### ISSUE THREAD

**Issue by coderwassananmol** [zero-gravity-org/zero-gravity-website#6]

**Comment by hyp3r5pace** [comment]
I want to work on this issue

**Comment by coderwassananmol** [comment]
Feel free to send PR @Maxz2136 :)

**Comment by asha15** [comment]
HI, I want to work on this issue

**Comment by goelaakash79** [comment]
Can I solve this issue?

**Comment by vaibhav-sharma-frontend** [comment]
@coderwassananmol  can I take this issue?

**Comment by coderwassananmol** [comment]
@vsharma20v 

> @coderwassananmol can I take this issue?

Sure. Go for it.

**Comment by coderwassananmol** [comment]
> @coderwassananmol can I take this issue?

There is already an active PR for this issue: #20

**Comment by coderwassananmol** [comment]
Issue resolved.
